name: CI/CD
on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    name: Lint Files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Lint Files
        run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/siemaapplications/zephyr-arm-build
      - name: show docker meta infos
        run: |
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
